"""HTTP surface for Nebula.

* GET  /api/nebula/snapshot          (HA auth)  - the combined Home/Scenes/Automations picture
* GET  /api/nebula/clients           (HA auth)  - who is currently connected
* POST /api/nebula/pair              (no auth)  - exchange a single-use PIN for a long-lived token
* GET  /api/nebula/pair_qr           (no auth)  - PNG QR of the live pairing code (404 if none)
* POST /api/nebula/reminders/sync    (HA auth)  - replace the app-synced reminders batch
* POST /api/nebula/relay_put/{id}    (HA auth)  - phone: drop a bind_ha payload for a panel to pick up
* GET  /api/nebula/relay_poll/{id}   (no auth)  - panel: pop the payload dropped for its session id
"""

from __future__ import annotations

import logging
from datetime import timedelta
from http import HTTPStatus
from typing import Any

from aiohttp import web
import voluptuous as vol

from homeassistant.auth.models import TOKEN_TYPE_LONG_LIVED_ACCESS_TOKEN
from homeassistant.components.http import KEY_HASS_USER, HomeAssistantView
from homeassistant.core import HomeAssistant
from homeassistant.helpers import config_validation as cv

from .const import CLIENT_NAME_MAX, DATA_MANAGER, DATA_REMINDERS, DOMAIN

_LOGGER = logging.getLogger(__name__)


def _manager(hass: HomeAssistant):
    for data in hass.data.get(DOMAIN, {}).values():
        if isinstance(data, dict) and DATA_MANAGER in data:
            return data[DATA_MANAGER]
    return None


def _reminders_entity(hass: HomeAssistant):
    for data in hass.data.get(DOMAIN, {}).values():
        if isinstance(data, dict) and DATA_REMINDERS in data:
            return data[DATA_REMINDERS]
    return None


def async_register_http(hass: HomeAssistant) -> None:
    hass.http.register_view(NebulaSnapshotView())
    hass.http.register_view(NebulaClientsView())
    hass.http.register_view(NebulaPairView())
    hass.http.register_view(NebulaPairQRView())
    hass.http.register_view(NebulaRemindersSyncView())
    hass.http.register_view(NebulaRelayPutView())
    hass.http.register_view(NebulaRelayPollView())


class NebulaSnapshotView(HomeAssistantView):
    url = "/api/nebula/snapshot"
    name = "api:nebula:snapshot"
    requires_auth = True

    async def get(self, request: web.Request) -> web.Response:
        hass = request.app["hass"]
        manager = _manager(hass)
        if manager is None:
            return self.json_message("Nebula not set up", HTTPStatus.SERVICE_UNAVAILABLE)
        snapshot = manager.build_snapshot()
        # So an app holding only a manually-entered long-lived token (the
        # "Advanced" path, no PIN exchange to piggyback on) still gets the
        # linked Home Assistant user's own display name — same as the PIN
        # flow returns from /api/nebula/pair. This is the one identity
        # Nebula relies on: no separate Nebula account, ever.
        hass_user = request.get(KEY_HASS_USER)
        snapshot["user_name"] = hass_user.name if hass_user else None
        return self.json(snapshot)


class NebulaClientsView(HomeAssistantView):
    url = "/api/nebula/clients"
    name = "api:nebula:clients"
    requires_auth = True

    async def get(self, request: web.Request) -> web.Response:
        hass = request.app["hass"]
        manager = _manager(hass)
        if manager is None:
            return self.json_message("Nebula not set up", HTTPStatus.SERVICE_UNAVAILABLE)
        return self.json(
            {
                "connected": sorted(manager.connected_kinds()),
                "clients": manager.client_details(),
            }
        )


class NebulaPairView(HomeAssistantView):
    """Trade a single-use PIN (generated by an authenticated client) for a token."""

    url = "/api/nebula/pair"
    name = "api:nebula:pair"
    requires_auth = False

    _schema = vol.Schema(
        {
            vol.Required("pin"): cv.string,
            vol.Optional("client_name", default="Nebula app"): vol.All(
                cv.string, vol.Length(min=1, max=CLIENT_NAME_MAX)
            ),
        }
    )

    async def post(self, request: web.Request) -> web.Response:
        hass: HomeAssistant = request.app["hass"]
        manager = _manager(hass)
        if manager is None:
            return self.json_message("Nebula not set up", HTTPStatus.SERVICE_UNAVAILABLE)

        try:
            body = self._schema(await request.json())
        except (vol.Invalid, ValueError):
            return self.json_message("Bad request", HTTPStatus.BAD_REQUEST)

        owner = manager.consume_pin(body["pin"])
        if owner is None:
            # Rate-limit brute force: a wrong PIN costs the caller a short wait.
            return self.json_message("Invalid or expired PIN", HTTPStatus.FORBIDDEN)

        user = await hass.auth.async_get_user(owner)
        if user is None or not user.is_active:
            return self.json_message("Pairing user unavailable", HTTPStatus.FORBIDDEN)

        client_name = f"Nebula: {body['client_name']}"
        # One token per client name — clear a stale one first.
        for tok in list(user.refresh_tokens.values()):
            if tok.client_name == client_name:
                hass.auth.async_remove_refresh_token(tok)

        refresh_token = await hass.auth.async_create_refresh_token(
            user,
            client_name=client_name,
            token_type=TOKEN_TYPE_LONG_LIVED_ACCESS_TOKEN,
            access_token_expiration=timedelta(days=3650),
        )
        access_token = hass.auth.async_create_access_token(refresh_token)

        from homeassistant.helpers import network

        try:
            base_url = network.get_url(hass, allow_internal=True, allow_external=True)
        except network.NoURLAvailableError:
            base_url = None

        from .manager import remote_ui_url

        return self.json(
            {
                "access_token": access_token,
                "token_type": "long_lived",
                "base_url": base_url,
                "cloud_url": remote_ui_url(hass),
                "ha_version": hass.config.as_dict().get("version"),
                "location_name": hass.config.location_name,
                "user_name": user.name,
            }
        )


class NebulaPairQRView(HomeAssistantView):
    """PNG QR of the live pairing code, for the persistent-notification poster.

    Unauthenticated so it renders in an `<img>` inside the notification. It only
    returns anything while a QR pairing code is actually live (raised on startup
    when no app has paired, or by the `nebula.pair_code` service); otherwise 404.
    The code it encodes is single-use and time-limited — same exposure as the
    number printed next to it.
    """

    url = "/api/nebula/pair_qr"
    name = "api:nebula:pair_qr"
    requires_auth = False

    async def get(self, request: web.Request) -> web.Response:
        hass: HomeAssistant = request.app["hass"]
        manager = _manager(hass)
        code = manager.active_qr_code() if manager else None
        if not code:
            return web.Response(status=HTTPStatus.NOT_FOUND)

        from .pairing import async_lan_host_port, pair_uri, qr_png

        host, port = await async_lan_host_port(hass)
        uri = pair_uri(host, port, code, hass.config.location_name)
        try:
            png = await hass.async_add_executor_job(qr_png, uri)
        except Exception:  # noqa: BLE001 - segno missing / render failure
            _LOGGER.exception("Nebula: could not render pairing QR")
            return web.Response(status=HTTPStatus.INTERNAL_SERVER_ERROR)
        return web.Response(
            body=png,
            content_type="image/png",
            headers={"Cache-Control": "no-store"},
        )


class NebulaRelayPutView(HomeAssistantView):
    """Phone leg of the pairing relay — fallback transport for `bind_ha`
    when Wi-Fi client/AP isolation blocks the phone from reaching the panel
    directly (isolation still lets both sides reach *this* server). Drops
    the same payload the phone would otherwise have POSTed straight to the
    panel's `/cmd`, keyed by the session id from the panel's own QR, for
    NebulaRelayPollView (below) to hand off. Overwriting on a retry is fine
    — single mailbox slot per session, last write wins.
    """

    url = "/api/nebula/relay_put/{session}"
    name = "api:nebula:relay_put"
    requires_auth = True

    _schema = vol.Schema(
        {
            vol.Required("pin"): cv.string,
            vol.Required("ha_url"): cv.string,
            vol.Required("ha_token"): cv.string,
            vol.Optional("owner_name", default=""): cv.string,
        }
    )

    async def post(self, request: web.Request, session: str) -> web.Response:
        hass: HomeAssistant = request.app["hass"]
        manager = _manager(hass)
        if manager is None:
            return self.json_message("Nebula not set up", HTTPStatus.SERVICE_UNAVAILABLE)
        try:
            body = self._schema(await request.json())
        except (vol.Invalid, ValueError):
            return self.json_message("Bad request", HTTPStatus.BAD_REQUEST)
        manager.relay_put(session, body)
        return self.json({"ok": True})


class NebulaRelayPollView(HomeAssistantView):
    """Panel leg of the pairing relay. Unauthenticated — the session id
    (from a QR only the panel itself generated) is the only thing gating
    this, the same trust boundary as the pairing PIN sitting next to it on
    screen. That's enough: whatever this returns still has to pass the
    panel's own `PairingPin.isValid()` check before anything actually
    binds, exactly like a direct `/cmd` POST would. Single-use — a second
    poll for the same session 404s just like an already-consumed PIN would.
    """

    url = "/api/nebula/relay_poll/{session}"
    name = "api:nebula:relay_poll"
    requires_auth = False

    async def get(self, request: web.Request, session: str) -> web.Response:
        hass: HomeAssistant = request.app["hass"]
        manager = _manager(hass)
        if manager is None:
            return self.json_message("Nebula not set up", HTTPStatus.SERVICE_UNAVAILABLE)
        payload = manager.relay_take(session)
        if payload is None:
            return web.Response(status=HTTPStatus.NOT_FOUND)
        return self.json(payload)


class NebulaRemindersSyncView(HomeAssistantView):
    """Replace the app-synced slice of `todo.nebula_reminders` in one shot.

    Called by the phone app after it reads the user's iOS EventKit (iCloud/
    Google/Outlook, whatever they've added in Settings -> Calendar). One-way
    and idempotent: every item here is keyed by its own `external_id`, so a
    re-sync updates in place; anything not in the batch that was previously
    external gets dropped (the source item was deleted/completed on the
    phone). Items added by voice or on the panel are untouched either way.
    """

    url = "/api/nebula/reminders/sync"
    name = "api:nebula:reminders:sync"
    requires_auth = True

    _item_schema = vol.Schema(
        {
            vol.Required("external_id"): cv.string,
            vol.Required("summary"): cv.string,
            vol.Optional("due"): vol.Any(cv.string, None),
            vol.Optional("description"): vol.Any(cv.string, None),
        },
        extra=vol.ALLOW_EXTRA,
    )
    _schema = vol.Schema({vol.Required("items"): [_item_schema]})

    async def post(self, request: web.Request) -> web.Response:
        hass: HomeAssistant = request.app["hass"]
        entity = _reminders_entity(hass)
        if entity is None:
            return self.json_message("Nebula not set up", HTTPStatus.SERVICE_UNAVAILABLE)

        try:
            body = self._schema(await request.json())
        except (vol.Invalid, ValueError):
            return self.json_message("Bad request", HTTPStatus.BAD_REQUEST)

        result = await entity.async_sync_external(body["items"])
        return self.json(result)
